"""create projects and project members

Revision ID: c772197ddc53
Revises: 0883628897c2
Create Date: 2026-10-07 09:38:42.705183

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c772197ddc53"
down_revision: str | Sequence[str] | None = "0883628897c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("projects_pkey")),
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "member", name="project_role"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("project_members_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("project_members_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "user_id", name=op.f("project_members_pkey")
        ),
    )
    op.create_index(
        "ix_project_members_user_id_project_id",
        "project_members",
        ["user_id", "project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_project_members_user_id_project_id",
        table_name="project_members",
    )
    op.drop_table("project_members")
    op.drop_table("projects")

    sa.Enum(
        "owner",
        "admin",
        "member",
        name="project_role",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
